function [H] = createTransform(alpha, beta, gamma, x, y, z)
% Creates homogeous transformation matrix
% alpha, beta, gamma - Euler angles xy'z''
% x, y, z - translations corresponding to each axis

Rx = [1 0 0 0; ...
    0 cos(alpha) -sin(alpha) 0; ...
    0 sin(alpha) cos(alpha) 0; ...
    0 0 0 1];
Ry = [cos(beta) 0 sin(beta) 0; ...
    0 1 0 0; ...
    -sin(beta) 0 cos(beta) 0; ...
    0 0 0 1];
Rz = [cos(gamma) -sin(gamma) 0 0; ...
    sin(gamma) cos(gamma) 0 0; ...
    0 0 1 0;
    0 0 0 1];
T = [1 0 0 x; ...
    0 1 0 y; ...
    0 0 1 z; ...
    0 0 0 1];

H = Rx * Ry * Rz * T;

end

